version = 0.1
[default.deploy.parameters]
stack_name = "module-3-kinesis-integratioN"
resolve_s3 = true
s3_prefix = "module-3-kinesis-integratioN"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KinesisStreamName=\"KinesisStreamAPIGW\""
image_repositories = []
