    
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
   module3-kinesis: Sample SAM Template for module3-kinesis

Globals:

    #Enable Logs
    Api:
        MethodSettings:
            - ResourcePath: "/*"
              HttpMethod: "*"
              DataTraceEnabled: True
              LoggingLevel: INFO
              MetricsEnabled: True
    Function:
        Timeout: 3
        Runtime: nodejs18.x
Parameters:
  KinesisStreamName:
    Type: String
    Default: KinesisStreamAPIGW

Resources:

  #Create the Kinesis Data Stream
  KinesisStreamAPIGW:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Ref KinesisStreamName
      StreamModeDetails: 
        StreamMode: ON_DEMAND
   
  #Create the IAM role      
  IAMRoleForKinesisIntegration:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: PolicyForAPIGWKinesisIntegration
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'kinesis:PutRecord'
                Resource: !GetAtt KinesisStreamAPIGW.Arn
    
  # Create the API Gateway 
  APIWithKinsesisIntegration:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      OpenApiVersion: 3.0.3
      DefinitionBody: # an OpenApi definition
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: "openapi.yaml"
      EndpointConfiguration:
          Type: REGIONAL
              
    # Lambda to Consume from Kinesis
  
  GetRecordsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./handlers
      Handler: get-records.handler
      Policies:
        - KinesisCrudPolicy:
            StreamName: !Ref KinesisStreamName
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt KinesisStreamAPIGW.Arn
            BatchSize: 100
            StartingPosition: LATEST
Outputs:
  APIGatewayEndpoint:
    Description: API Gateway Endpoint
    Value: !Sub https://${APIWithKinsesisIntegration}.execute-api.${AWS::Region}.amazonaws.com/dev/streams/${KinesisStreamName}/record
  KinesisARN:
    Description: ARN for Kinesis data stream
    Value: !GetAtt KinesisStreamAPIGW.Arn