AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for my first API with IaC

Globals:
  # Enable Logs
  Api:
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          DataTraceEnabled: True
          LoggingLevel: INFO
          MetricsEnabled: True
  Function:
    Timeout: 3
    Runtime: nodejs18.x

Resources:
  # REST API                                                             
  FirstAPI:
    Type: AWS::Serverless::Api
    Properties:
        StageName: dev
        OpenApiVersion: 3.0.3
        DefinitionBody: # an OpenApi definition
          "Fn::Transform":
            Name: "AWS::Include"
            Parameters:
                Location: "openapi.yaml"
        EndpointConfiguration:
          Type: REGIONAL

  # Lambda functions                                                     
  CostCalculator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: cost-calculator.CostCalculator

  # Declares a Cognito user pool
  CostCalculatorUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
          UserPoolName: CostCalculatorUserPool
          Policies:
              PasswordPolicy:
                  MinimumLength: 8
  # Declares a Cognito user pool client that references our user pool
  CostCalculatorUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
          UserPoolId: !Ref CostCalculatorUserPool
          ClientName: Cost-Calculator-App-Client
          GenerateSecret: false
          ExplicitAuthFlows:
              - ALLOW_ADMIN_USER_PASSWORD_AUTH
              - ALLOW_REFRESH_TOKEN_AUTH
              - ALLOW_CUSTOM_AUTH
              - ALLOW_USER_PASSWORD_AUTH
              - ALLOW_USER_SRP_AUTH      
          
  # Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: AllowLambdaExec
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: !GetAtt CostCalculator.Arn

Outputs:
  FirstAPI:
    Description: "API Gateway endpoint URL to call my first api"
    Value: !Sub "https://${FirstAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  CognitoUserPool:
    Description: "Cognito User Pool Id"
    Value: !Ref CostCalculatorUserPool
  CostCalculatorUserPoolClient:
    Description: "App Client Id"
    Value: !Ref CostCalculatorUserPoolClient