openapi: "3.0.1"
info:
  title: "module-3-dynamodb-integration"
  description: "API Gateway example for Amazon DynamoDB Integration"
  version: "1.0"
paths:
  /resource:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: 
          Fn::Sub: "${RestApiRole.Arn}"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:${AWS::Region}:dynamodb:action/Query"
        responses:
          default:
            statusCode: "200"
            responseTemplates:
              application/json: "#set($inputRoot = $input.path('$'))\n{\n    \"Names\"\
                : [\n        #foreach($elem in $inputRoot.Items) {\n            \"\
                id\": \"$elem.id.S\",\n            \"name\": \"$elem.name.S\",\n \
                \           \"lastName\": \"$elem.lastName.S\",\n            \"email\"\
                : \"$elem.email.S\"\n        }#if($foreach.hasNext),#end\n\t#end\n\
                \    ]\n}"
        requestTemplates:
          application/json: "{\n    \"TableName\": \"MyTable\",\n    \"KeyConditionExpression\"\
            : \"id = :v1\",\n    \"ExpressionAttributeValues\": {\n        \":v1\"\
            : {\n            \"S\": \"$input.params('id')\"\n        }\n    }\n}\n"
        passthroughBehavior: "when_no_templates"
  /resource/{id}:
    post:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        type: "aws"
        credentials: 
          Fn::Sub: "${RestApiRole.Arn}"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:${AWS::Region}:dynamodb:action/PutItem"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: "{ \n    \"TableName\": \"MyTable\",\n    \"Item\": {\n\
            \t    \"id\": {\n            \"S\": \"$input.params('id')\"\n        \
            \    },\n        \"name\": {\n            \"S\": \"$input.path('$.name')\"\
            \n            },\n        \"lastName\": {\n            \"S\": \"$input.path('$.lastName')\"\
            \n        },\n        \"email\": {\n            \"S\": \"$input.path('$.email')\"\
            \n        }\n    }\n}"
        passthroughBehavior: "when_no_templates"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
