version = 0.1
[default.deploy.parameters]
stack_name = "module-5-websocket"
resolve_s3 = true
s3_prefix = "module-5-websocket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApiStageName=\"Y\""
image_repositories = []
