AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  module4-observability: Sample SAM Template for module4-observability


Resources:
    # Our API Gateway API
    ObservabilityAPI:
        Type: AWS::Serverless::Api
        Properties:
            StageName: dev
            OpenApiVersion: 3.0.3
            DefinitionBody: # an OpenApi definition
                "Fn::Transform":
                    Name: "AWS::Include"
                    Parameters:
                        Location: "openapi.yaml"
            EndpointConfiguration:
                Type: REGIONAL

    #Lambda Function used to generate the required data points
    FunctionForDataPoints:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: ./handlers/code
            Handler: generate-data.handler
            Timeout: 1
            Runtime: nodejs18.x
    # Execution Role for lambda functions
    LambdaExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: Allow
                    Principal:
                      Service:
                        - apigateway.amazonaws.com
                    Action:
                      - 'sts:AssumeRole'
            Policies:
                - PolicyName: AllowLambdaExec
                  PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Effect: Allow
                        Action: 'lambda:InvokeFunction'
                        Resource: [
                            !GetAtt FunctionForDataPoints.Arn, 
                        ]        

Outputs:
    APIGatewayInvokeURL:
        Description: API Gateway Endpoint for logging example
        Value:
            Fn::Sub: https://${ObservabilityAPI}.execute-api.${AWS::Region}.amazonaws.com/dev/generate-data
    LogInsightsKeyword:
        Description: Keyword needed to filter for this api logs
        Value:
          Fn::Sub: API-Gateway-Execution-Logs_${ObservabilityAPI}/dev