AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  API Gateway example for AWS Step Functions Integration

Globals:

    # Enable Logs
    Api:
        MethodSettings:
            - ResourcePath: "/*"
              HttpMethod: "*"
              DataTraceEnabled: True
              LoggingLevel: INFO
              MetricsEnabled: True


Resources:

  # Step Functions Express Definition
  StateMachineExpress:
    Type: AWS::Serverless::StateMachine 
    Properties:
      Name: StateMachineExpress
      DefinitionUri: state-machine/step-function.asl.json
      Policies:
        -  Version: "2012-10-17"
           Statement:
             - Effect: Allow
               Action:
                 - "cloudwatch:*"
                 - "logs:*"
               Resource: "*"
      Type: EXPRESS
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        IncludeExecutionData: false
        Level: 'ALL'
        
  # Log group for Express Step Functions
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ "/", [ "stepfunctions", StateMachineExpress]]
      
  # Step Functions Standard Definition
  StateMachineStandard:
    Type: AWS::Serverless::StateMachine 
    Properties:
      Name: StateMachineStandard
      DefinitionUri: state-machine/step-function.asl.json
      Policies:
        -  Version: "2012-10-17"
           Statement:
             - Effect: Allow
               Action:
                 - "cloudwatch:*"
                 - "logs:*"
               Resource: "*"
      Type: STANDARD

  # APIGW Rest API for Step Functions Integration Example
  RestApiforSyncWF:
     Type: AWS::Serverless::Api
     Properties:
        StageName: dev
        DefinitionBody: # an OpenApi definition
          'Fn::Transform':
            Name: 'AWS::Include'
            Parameters:
              Location: 'openapi.yaml'
        OpenApiVersion: 3.0.3
        EndpointConfiguration:
            Type: REGIONAL
        Variables:
          SFARNEXPRESS: !GetAtt StateMachineExpress.Arn
          SFARNSTANDARD: !GetAtt StateMachineStandard.Arn
          
  # IAM Role to allow APIGW to call SF Express and Standard
  RestApiRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
      - PolicyName: AllowSFNExec
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - "states:StartSyncExecution"
                - "states:StartExecution"
              Resource: 
                - !GetAtt StateMachineExpress.Arn
                - !GetAtt StateMachineStandard.Arn

Outputs:
  ExpressSFIntegrationRestAPI:
    Description: "Express Workflow API endpoint"
    Value: !Sub "https://${RestApiforSyncWF}.execute-api.${AWS::Region}.amazonaws.com/dev"
    
  ExpressStepFunctionsArn:
    Description: "Step Functions Express ARN"
    Value: !GetAtt StateMachineExpress.Arn
    
  StandardStepFunctionsArn:
    Description: "Step Functions Standard ARN"
    Value: !GetAtt StateMachineStandard.Arn
